# --IMPORTANT--
BOT_TOKEN = 'BOT_TOKEN_HERE'
ADMIN_USERNAME = '_.marzz._'

# --FILE PATHS--
BACKUP_FILE_PATH = './data/backup.json'
LOG_FILE_PATH = './data/passes_info.txt'

# --CHANNEL IDS--
NOTIFICATION_CHANNEL_ID = CHANNEL_ID_HERE
STATUS_CHANNEL_ID = CHANNEL_ID_HERE
LEADERBOARD_CHANNEL_ID = CHANNEL_ID_HERE
